name: bioportal-rest

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  solr:
    image: ontoportal/solr-ut:0.2.0
    ports:
      - '8983:8983'

  mgrep:
    image: ontoportal/mgrep:0.0.3
    platform: linux/amd64
    ports:
      - '55556:55556'

  agraph:
    image: franzinc/agraph:v8.1.1
    platform: linux/amd64
    profiles:
      - agraph
    env_file:
      - path: ./development.env
        required: true
    shm_size: 1g
    ports:
      - '10035:10035'
    command: >
      bash -c "/agraph/bin/agraph-control --config /agraph/etc/agraph.cfg start;
               agtool repos create bioportal;
               agtool users add anonymous;
               agtool users grant anonymous root:bioportal:rw;
               tail -f /agraph/data/agraph.log;"

  fourstore:
    image: bde2020/4store
    platform: linux/amd64
    profiles:
      - fs
      - 4store
    ports:
      - '9000:9000'
    volumes:
      - 4store-data:/var/lib/4store
    command: >
      bash -c "4s-backend-setup bioportal &&
               4s-backend bioportal &&
               4s-httpd -D -s-1 -p 9000 bioportal"

volumes:
  4store-data: