version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  solr:
    image: ontoportal/solr-ut:0.1.0
    ports:
      - '8983:8983'

  mgrep:
    image: ontoportal/mgrep:0.0.2
    platform: linux/amd64
    ports:
      - '55556:55556'

  agraph:
    image: franzinc/agraph:v8.0.1
    platform: linux/amd64
    env_file:
      - path: ./development.env
        required: true
    shm_size: 1g
    ports:
      - '10035:10035'
    command: >
      bash -c "/agraph/bin/agraph-control --config /agraph/etc/agraph.cfg start;
               agtool repos create bioportal;
               agtool users add anonymous;
               agtool users grant anonymous root:bioportal:rw;
               tail -f /agraph/data/agraph.log;"